/* ============================================================
   Customer Shopping Behavior — SQL Business Analysis
   Database: customer_behavior   |   Table: customers (3,900 rows)
   Engine:   PostgreSQL
   Author:   Manas Jaiswal
   ------------------------------------------------------------
   The cleaned dataset was loaded from Python (pandas) into
   PostgreSQL via SQLAlchemy. The 10 queries below answer the
   project's core business questions.
   ============================================================ */


-- Q1. Total revenue generated by male vs. female customers
SELECT gender,
       SUM(purchase_amount) AS revenue
FROM customers
GROUP BY gender;


-- Q2. Customers who used a discount but still spent MORE than the
--     overall average purchase amount (uses a subquery)
SELECT customer_id,
       purchase_amount
FROM customers
WHERE discount_applied = 'Yes'
  AND purchase_amount > (SELECT AVG(purchase_amount) FROM customers)
ORDER BY purchase_amount DESC;


-- Q3. Top 5 products by average review rating
--     review_rating is double precision, so cast to numeric for ROUND(x, 2)
SELECT item_purchased,
       ROUND(AVG(review_rating::numeric), 2) AS avg_product_rating
FROM customers
GROUP BY item_purchased
ORDER BY avg_product_rating DESC
LIMIT 5;


-- Q4. Average purchase amount: Standard vs. Express shipping
SELECT shipping_type,
       ROUND(AVG(purchase_amount)::numeric, 2) AS avg_purchase_amount
FROM customers
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;


-- Q5. Do subscribers spend more?
--     Compare customer count, average spend and total revenue
SELECT subscription_status,
       COUNT(customer_id)                        AS total_customers,
       ROUND(AVG(purchase_amount)::numeric, 2)   AS avg_spend,
       SUM(purchase_amount)                      AS total_revenue
FROM customers
GROUP BY subscription_status
ORDER BY total_revenue DESC, avg_spend DESC;


-- Q6. Top 5 products with the highest % of purchases made with a discount
--     (100.0 forces decimal division so the rate isn't truncated to an int)
SELECT item_purchased,
       ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)
             / COUNT(*), 2) AS discount_rate
FROM customers
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;


-- Q7. Segment customers into New / Returning / Loyal by previous purchases,
--     then count each segment (uses a CTE + CASE)
WITH customer_type AS (
    SELECT customer_id,
           previous_purchases,
           CASE
               WHEN previous_purchases = 1            THEN 'New'
               WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
               ELSE 'Loyal'
           END AS customer_segment
    FROM customers
)
SELECT customer_segment,
       COUNT(*) AS number_of_customers
FROM customer_type
GROUP BY customer_segment;


-- Q8. Top 3 most-purchased products within each category
--     (window function; ROW_NUMBER breaks ties so exactly 3 rows per category)
WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (
               PARTITION BY category
               ORDER BY COUNT(customer_id) DESC
           ) AS item_rank
    FROM customers
    GROUP BY category, item_purchased
)
SELECT item_rank,
       category,
       item_purchased,
       total_orders
FROM item_counts
WHERE item_rank <= 3;


-- Q9. Are repeat buyers (5+ previous purchases) also likely to subscribe?
SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM customers
WHERE previous_purchases > 5
GROUP BY subscription_status;


-- Q10. Revenue contribution by age group
SELECT age_group,
       SUM(purchase_amount) AS total_revenue
FROM customers
GROUP BY age_group
ORDER BY total_revenue DESC;
